name: MarketShop
main: ZenSageX444\MarketShop\Market
version: 1.0.0
api: 5.0.0
author: ゼンセージ_X, DARUMA/んひた
website: https://github.com/ZenSageX444/MarketShop
discord: https://discord.com/invite/NDD6PeJZNC
virions: ["InvMenu"]
depend:
  - BedrockEconomy
